GET https://tester-web-api.onrender.com//formjson

###

POST https://tester-web-api.onrender.com//register
Content-Type: application/json

{
  "email": "atharvdesai2002@gmail.com",
  "password": "12345678"
}
